# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 ComfyUI-GeometryPack Contributors

"""
Remeshing nodes (main dependencies only)
"""

from .refine import NODE_CLASS_MAPPINGS as REFINE_MAPS, NODE_DISPLAY_NAME_MAPPINGS as REFINE_DISP
from .remesh import NODE_CLASS_MAPPINGS as REMESH_MAPS, NODE_DISPLAY_NAME_MAPPINGS as REMESH_DISP

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(REFINE_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(REFINE_DISP)
NODE_CLASS_MAPPINGS.update(REMESH_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(REMESH_DISP)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
