# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 ComfyUI-GeometryPack Contributors

"""Analysis module - mesh information and quality metrics."""

from .mesh_info import NODE_CLASS_MAPPINGS as MESH_INFO_MAPPINGS
from .mesh_info import NODE_DISPLAY_NAME_MAPPINGS as MESH_INFO_DISPLAY
from .mesh_quality import NODE_CLASS_MAPPINGS as MESH_QUALITY_MAPPINGS
from .mesh_quality import NODE_DISPLAY_NAME_MAPPINGS as MESH_QUALITY_DISPLAY
from .connected_components import NODE_CLASS_MAPPINGS as CONNECTED_COMPONENTS_MAPPINGS
from .connected_components import NODE_DISPLAY_NAME_MAPPINGS as CONNECTED_COMPONENTS_DISPLAY
from .open_edges import NODE_CLASS_MAPPINGS as OPEN_EDGES_MAPPINGS
from .open_edges import NODE_DISPLAY_NAME_MAPPINGS as OPEN_EDGES_DISPLAY
from .degenerate_faces import NODE_CLASS_MAPPINGS as DEGENERATE_FACES_MAPPINGS
from .degenerate_faces import NODE_DISPLAY_NAME_MAPPINGS as DEGENERATE_FACES_DISPLAY
from .scramble_field import NODE_CLASS_MAPPINGS as SCRAMBLE_FIELD_MAPPINGS
from .scramble_field import NODE_DISPLAY_NAME_MAPPINGS as SCRAMBLE_FIELD_DISPLAY

# Combine all mappings
NODE_CLASS_MAPPINGS = {
    **MESH_INFO_MAPPINGS,
    **MESH_QUALITY_MAPPINGS,
    **CONNECTED_COMPONENTS_MAPPINGS,
    **OPEN_EDGES_MAPPINGS,
    **DEGENERATE_FACES_MAPPINGS,
    **SCRAMBLE_FIELD_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **MESH_INFO_DISPLAY,
    **MESH_QUALITY_DISPLAY,
    **CONNECTED_COMPONENTS_DISPLAY,
    **OPEN_EDGES_DISPLAY,
    **DEGENERATE_FACES_DISPLAY,
    **SCRAMBLE_FIELD_DISPLAY,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
